Repository etendosoftware/etendo_core, pull requests merged in 2024-04, with the labels that each got.

#352 Issue #343: Add 'refreshParent' property to the response actions
  src/org/openbravo/common/actionhandler/CopyFromOrdersActionHandler.java
Labels: bug

#353 Issue #326: Add Document Type existence check for Post/Unpost process
  src-db/database/sourcedata/AD_MESSAGE.xml
  src-test/src/org/openbravo/test/costing/TestCostingBase.java
  src-test/src/org/openbravo/test/costing/utils/TestCostingConstants.java
  src/org/openbravo/erpCommon/ad_forms/AcctServer.java
  src/org/openbravo/erpCommon/ad_forms/AcctServer_data.xsql
  src/org/openbravo/financial/ResetAccounting.java
Labels: bug

#355 Hotfix ETO-308: Upgrade tomcat version in pipelines
  pipelines/unittests/Jenkinsfile
  pipelines/unittests/JenkinsfileOracle
Labels: enhancement

#356 Issue #256: Unchanged Index is exported in template
  src-db/database/model/tables/AD_SEQUENCE.xml
Labels: bug

#357 Issue #343: Add 'refreshParent' property to the BaseProcessActionHandler process
  modules_core/org.openbravo.client.application/src/org/openbravo/client/application/process/BaseProcessActionHandler.java
  src/org/openbravo/common/actionhandler/CopyFromOrdersActionHandler.java
Labels: bug

#359 Issue #358: Fix error that made posting return empty error messages
  src-db/database/sourcedata/AD_REF_LIST.xml
  src/org/openbravo/erpCommon/ad_forms/AcctServer.java
Labels: bug

#365 Issue #322: Change the SessionHandler to OBDal on rollback method
  modules_core/org.openbravo.advpaymentmngt/src/org/openbravo/advpaymentmngt/actionHandler/AddPaymentActionHandler.java
Labels: bug

#377 Feature ETO-298: Add configuration for sonarqube gradle task
  build.gradle
  gradle.properties.template
Labels: enhancement, sonarqube

#370 Issue #369: Correct error handling when deleting accounting data
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src-test/src/org/openbravo/test/accounting/PostedNoDocConfigTest.java
  src/org/openbravo/financial/ResetAccounting.java
Labels: bug

#374 Issue #299: taxes without father are removed upon completion
  src-db/database/model/functions/C_INVOICE_UPDATE_TAXES.xml
  src-db/database/model/functions/C_ORDER_UPDATE_TAXES.xml
  src-db/database/model/triggers/C_INVOICELINETAX_TRG.xml
  src-db/database/model/triggers/C_ORDERLINETAX_TRG.xml
  src-db/database/sourcedata/AD_EP_PROCEDURES.xml
  src-test/src/org/openbravo/test/taxes/TaxesTest.java
Labels: bug

#379 Issue #369: fix call function to work on oracle
  src-test/src/org/openbravo/test/accounting/PostedNoDocConfigTest.java
Labels: bug

#373 Issue #361: Add custom logout redirection functionality to Etendo
  modules_core/org.openbravo.client.application/web/org.openbravo.client.application/js/utilities/ob-utilities.js
  modules_core/org.openbravo.client.kernel/src/org/openbravo/client/kernel/ApplicationComponent.java
  modules_core/org.openbravo.client.kernel/src/org/openbravo/client/kernel/KernelConstants.java
  modules_core/org.openbravo.client.kernel/src/org/openbravo/client/kernel/templates/application-js.ftl
  src-db/database/sourcedata/AD_PREFERENCE.xml
  src-db/database/sourcedata/AD_REF_LIST.xml
Labels: bug
