Repository etendosoftware/etendo_core, pull requests merged in 2024-05, with the labels that each got.

#383 Hotfix ETO-314: Remove 'Restart Environment' stage from pipelines
  pipelines/unittests/Jenkinsfile
  pipelines/unittests/JenkinsfileOracle
  pipelines/unittests/utils/infoCommit.groovy
  pipelines/unittests/utils/stackConfig.groovy
Labels: enhancement

#384 Issue #368: Change button behavior and add a loader
  src/org/openbravo/erpCommon/ad_forms/UpdateReferenceData.html
Labels: bug

#395 Issue #362: Fix to the error while printing products
  .github/workflows/build.yml
  src-test/resources/reports/Main.jrxml
  src-test/resources/reports/Subreport.jrxml
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src-test/src/org/openbravo/test/reporting/ReportingUtilsTest.java
  src/org/openbravo/dal/core/DalThreadCleaner.java
  src/org/openbravo/dal/core/DalThreadHandler.java
  src/org/openbravo/erpCommon/utility/Utility.java
  src/org/openbravo/erpReports/jasperreports.properties
  src/org/openbravo/report/jasper/SubreportRunner.java
  src/org/openbravo/report/jasper/SubreportRunnerFactory.java
Labels: bug

#392 Issue #388: Filter out inactive Orgs from 'Module Management' window
  src/org/openbravo/erpCommon/ad_forms/UpdateReferenceData_data.xsql
Labels: bug

#396 Feature ETO-325: Modify Sonarqube and Jacoco properties
  .github/workflows/build.yml
  build.gradle
  gradle.properties.template
Labels: enhancement

#399 Hotfix ETO-325: Add sonarqube properties
  .github/workflows/build.yml
  build.gradle
  gradle.properties.template
Labels: enhancement

#401 Issue #306: fix custom accounting for internal consumption
  src/org/openbravo/erpCommon/ad_forms/DocInternalConsumption.java
Labels: bug

#415 Issue #414: Set resources test dir for 'modules' and 'modules_core'
  pipelines/unittests/Jenkinsfile
  tests.gradle
Labels: bug, enhancement

#416 Hotfix ETO-346: Change access_token for update commit status
  pipelines/unittests/build-update.sh
Labels: enhancement
