Repository etendosoftware/etendo_core, pull requests merged in 2025-04, with the labels that each got.

#667 Issue #662: Fix BMP image MIME type detection
  src/org/openbravo/erpCommon/utility/MimeTypeUtil.java
Labels: bug

#670 Feature ETP-1364: Add unit tests
  src-test/src/org/openbravo/erpReports/ReportTaxPaymentJRTest.java
  src-test/src/org/openbravo/erpReports/RptC_InvoiceTest.java
  src-test/src/org/openbravo/erpReports/RptC_OrderTest.java
  src-test/src/org/openbravo/erpReports/RptC_ProposalJrTest.java
  src-test/src/org/openbravo/erpReports/RptC_RemittanceTest.java
  src-test/src/org/openbravo/erpReports/RptMA_ProcessPlanTest.java
  src-test/src/org/openbravo/erpReports/RptM_RequisitionTest.java
  src-test/src/org/openbravo/erpReports/TestUtils.java
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src/org/openbravo/erpReports/ReportTaxPaymentJR.java
  src/org/openbravo/erpReports/RptC_Bpartner.java
  src/org/openbravo/erpReports/RptC_Invoice.java
  src/org/openbravo/erpReports/RptC_Order.java
  src/org/openbravo/erpReports/RptC_ProposalJr.java
  src/org/openbravo/erpReports/RptC_Remittance.java
  src/org/openbravo/erpReports/RptMA_ProcessPlan.java
  src/org/openbravo/erpReports/RptM_Requisition.java
Labels: enhancement

#663 Issue #662: Fix BMP image MIME type detection
  src/org/openbravo/erpCommon/utility/MimeTypeUtil.java
Labels: bug

#659 Feature ETP-515: Restore missing warning in Valued Stock Report and enable support for messages in report logic
  modules_core/com.etendoerp.reportvaluationstock/src/com/etendoerp/reportvaluationstock/handler/ReportValuationStock.java
  modules_core/org.openbravo.client.application/src/org/openbravo/client/application/report/BaseReportActionHandler.java
  src-db/database/sourcedata/AD_MESSAGE.xml
  src-test/src/com/etendoerp/reportvaluationstock/handler/ReportValuationStockBuildDataTest.java
  src-test/src/com/etendoerp/reportvaluationstock/handler/ReportValuationStockHasTrxWithNoCostTest.java
  src-test/src/com/etendoerp/reportvaluationstock/handler/TestUtils.java
Labels: bug, enhancement

#671 Feature ETP-1341: Add unit tests for com.smf.mobile.utils module
  modules_core/com.smf.mobile.utils/src/com/smf/mobile/utils/webservices/Window.java
  src-test/src/com/smf/mobile/utils/webservices/FormValuesServiceTest.java
  src-test/src/com/smf/mobile/utils/webservices/VersionTest.java
  src-test/src/com/smf/mobile/utils/webservices/WBUtils.java
  src-test/src/com/smf/mobile/utils/webservices/WindowTest.java
  src-test/src/com/smf/mobile/utils/webservices/WindowUtilsTest.java
  src-test/src/com/smf/test/CoreTestSuite.java
Labels: testing

#672 Feature ETP-1416: Add JUnit 5 suite deps and refactor suites
  src-test/src/com/smf/test/CoreTestSuite.java
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src-test/src/org/openbravo/test/WebserviceTestSuite.java
  tests.gradle
Labels: testing

#684 Issue #680: Fix incorrect commission calculation
  src-db/database/model/functions/C_COMMISSION_PROCESS.xml
Labels: bug

#683 Issue #680: Fix incorrect commission calculation
  src-db/database/model/functions/C_COMMISSION_PROCESS.xml
Labels: bug

#685 Feature ETP-1460: Add unit tests
  src-test/src/org/openbravo/base/secureApp/AllowedCrossDomainsHandlerTest.java
  src-test/src/org/openbravo/base/secureApp/VariablesHistoryTest.java
  src-test/src/org/openbravo/cluster/ClusterServiceManagerTest.java
  src-test/src/org/openbravo/cluster/ClusterServiceTest.java
  src-test/src/org/openbravo/cluster/ClusterServiceThreadTest.java
  src-test/src/org/openbravo/cluster/JmxClusterServiceManagerTest.java
  src-test/src/org/openbravo/common/actionhandler/ActionHandlerTestConstants.java
  src-test/src/org/openbravo/common/actionhandler/AgingGeneralLedgerByOrganizationActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/CancelAndReplaceGetCancelledOrderLineTest.java
  src-test/src/org/openbravo/common/actionhandler/CancelAndReplaceSalesOrderTest.java
  src-test/src/org/openbravo/common/actionhandler/CashflowForecastReportActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/ConfirmCancelAndReplaceSalesOrderTest.java
  src-test/src/org/openbravo/common/actionhandler/CopyFromOrdersActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/CopyProcessPlanVersionTest.java
  src-test/src/org/openbravo/common/actionhandler/GetConvertedQtyActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/InvoiceFromShipmentActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/KillProcessTest.java
  src-test/src/org/openbravo/common/actionhandler/ManagePrereservationActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/ManageReservationActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/OrderCreatePOLinesTest.java
  src-test/src/org/openbravo/common/actionhandler/RelateProductCatTaxToServiceProductTest.java
  src-test/src/org/openbravo/common/actionhandler/RelateProductsToServiceProductTest.java
  src-test/src/org/openbravo/common/actionhandler/ReservedGoodMovementActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/ResetAccountingHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/ServiceRelatedLinePriceActionHandlerTest.java
  src-test/src/org/openbravo/common/actionhandler/createlinesfromprocess/InOutLineDataTest.java
  src-test/src/org/openbravo/common/datasource/InOutLinePEHQLTransformerTest.java
  src-test/src/org/openbravo/common/datasource/OrderLinePEHQLTransformerTest.java
  src-test/src/org/openbravo/common/datasource/OrderLinePickEditTransformerTest.java
  src-test/src/org/openbravo/common/datasource/ReturnToFromCustomerVendorHQLTransformerTest.java
  src-test/src/org/openbravo/common/datasource/ReturnToFromCustomerVendorOrphanHQLTransformerTest.java
  src-test/src/org/openbravo/common/datasource/ServiceModifyTaxProductCategoryTransformerTest.java
  src-test/src/org/openbravo/common/filterexpression/AgingOrganizationFilterExpressionTest.java
  src-test/src/org/openbravo/costing/CostAdjustmentProcessHandlerTest.java
  src-test/src/org/openbravo/erpCommon/ad_process/ScheduleProcessTest.java
  src-test/src/org/openbravo/portal/PortalEmailBodyTest.java
  src-test/src/org/openbravo/role/inheritance/RecalculatePermissionsHandlerTest.java
  src-test/src/org/openbravo/role/inheritance/RoleInheritanceWarningFICExtensionTest.java
  src-test/src/org/openbravo/service/centralrepository/CentralRepositoryPrivateMethodsTest.java
  src-test/src/org/openbravo/service/centralrepository/CentralRepositoryTest.java
  src-test/src/org/openbravo/service/centralrepository/CentralRepositoryTestConstants.java
  src-test/src/org/openbravo/service/centralrepository/ModuleDependencyTest.java
  src-test/src/org/openbravo/service/centralrepository/ModuleInstallDetailTest.java
  src-test/src/org/openbravo/service/centralrepository/ModuleTest.java
  src-test/src/org/openbravo/service/centralrepository/SimpleModuleTest.java
  src-test/src/org/openbravo/service/db/ClientImportProcessorTest.java
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src-test/src/org/openbravo/test/costing/TestIssue37279.java
  src/org/openbravo/erpCommon/ad_process/ScheduleProcess.java
  src/org/openbravo/service/centralrepository/ModuleDependency.java
  src/org/openbravo/service/centralrepository/ModuleInstallDetail.java
  src/org/openbravo/service/db/ClientImportProcessor.java
Labels: testing

#688 Issue #682: Fix Reservation Status after Reactivating and Booking SO
  src-db/database/model/functions/C_ORDER_POST1.xml
Labels: bug

#694 Issue #689: Fix cost total mismatch in Sales Invoice report
  src/org/openbravo/erpCommon/ad_reports/ReportInvoiceCustomerDimensionalAnalysesJR_data.xsql
Labels: bug

#690 Issue #682: Fix Reservation Status after Reactivating and Booking SO
  src-db/database/model/functions/C_ORDER_POST1.xml
Labels: bug

#692 Issue #689: Fix cost total mismatch in Sales Invoice report
  src/org/openbravo/erpCommon/ad_reports/ReportInvoiceCustomerDimensionalAnalysesJR_data.xsql
Labels: bug
