Repository etendosoftware/etendo_core, pull requests merged in 2025-05, with the labels that each got.

#686 Feature ETP-1525: Update Etendo License
  .gitignore
  LICENSE.md
  README.md
  legal/ASM_BSD_license.txt
  legal/Apache_poi_license.txt
  legal/BSD_license.txt
  legal/Etendo_license.txt
  legal/Etendo_privacy_policy.txt
  legal/LEGAL.md
  legal/Licensing.txt
  legal/Neko_license.txt
  legal/dom4j_license.txt
  modules_core/com.etendoerp.advpaymentmngt/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.etendoerp.client.application/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.etendoerp.legacy.advpaymentmngt/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.etendoerp.reportvaluationstock/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.jobs.defaults/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.jobs/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.mobile.utils/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.securewebservices/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.smartclient.boostedui/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.smartclient.debugtools/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.smf.userinterface.skin.legacy/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.advpaymentmngt/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.apachejdbcconnectionpool/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.base.weld/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.client.application/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.client.htmlwidget/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.client.kernel/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.client.myob/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.client.querylist/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.client.widgets/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.financial.paymentreport/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.reports.ordersawaitingdelivery/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.service.datasource/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.service.integration.google/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.service.json/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.userinterface.selector/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.userinterface.skin.250to300Comp/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.userinterface.smartclient/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.utility.cleanup.log/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.v3.datasets/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.v3.framework/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/org.openbravo.v3/src-db/database/sourcedata/AD_MODULE.xml
  src-db/database/sourcedata/AD_MODULE.xml
  src-db/database/sourcedata/AD_REF_LIST.xml
  src-db/database/sourcedata/AD_TEXTINTERFACES.xml
  src/org/openbravo/erpCommon/ad_forms/About.html
  src/org/openbravo/erpCommon/security/Login.html
Labels: documentation

#700 Issue #691: Fix duplication in Sales Invoices Dimensional Report
  src/org/openbravo/erpCommon/ad_reports/ReportInvoiceCustomerDimensionalAnalysesJR_data.xsql
Labels: bug

#702 Issue #691: Fix duplication in Sales Invoices Dimensional Report
  pipelines/unittests/Jenkinsfile
  pipelines/unittests/JenkinsfileOracle
  src/org/openbravo/erpCommon/ad_reports/ReportInvoiceCustomerDimensionalAnalysesJR_data.xsql
Labels: bug

#687 Feature ETP-1041: New login with Auth0
  artifacts.list.COMPILATION.gradle
  legal/LEGAL.md
  modules_core/com.smf.securewebservices/lib/runtime/java-jwt-3.1.0.jar
  modules_core/com.smf.securewebservices/web/com.smf.securewebservices/js/generateprivatekey.js
  src/org/openbravo/base/secureApp/LoginHandler.java
  src/org/openbravo/erpCommon/security/Login.html
  src/org/openbravo/erpCommon/security/Login.java
Labels: enhancement

#711 Issue #704: Improve localization and layout in CustomerStatement report
  src/org/openbravo/erpCommon/ad_reports/CustomerStatement.jrxml
Labels: bug

#706 Issue #693: Fix Discounts filters for characteristic inclusion
  src-db/database/model/functions/M_PROMOTION_CALCULATE.xml
  src/org/openbravo/erpCommon/businessUtility/PriceAdjustment.java
Labels: bug

#705 Issue #693: Fix Discounts filters for characteristic inclusion
  src-db/database/model/functions/M_PROMOTION_CALCULATE.xml
  src/org/openbravo/erpCommon/businessUtility/PriceAdjustment.java
Labels: bug

#722 Issue #717: Fix Alternative Taxable Amount on Copy From Order process
  src/org/openbravo/common/actionhandler/copyfromorderprocess/UpdatePricesAndAmounts.java
Labels: bug
