Repository etendosoftware/etendo_core, pull requests merged in 2025-01, with the labels that each got.

#567 Issue #529: Add user contact in Invoice creation from Goods Shipment
  src/org/openbravo/materialmgmt/InvoiceGeneratorFromGoodsShipment.java
Labels: bug, good first issue

#569 Issue #489: Automatic update of Landed Cost Distribution Algorithm
  src-test/src/org/openbravo/erpCommon/ad_callouts/LandedCostTypeTest.java
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src/org/openbravo/erpCommon/ad_callouts/SL_LandedCost_Cost_Type.java
Labels: bug

#566 Issue #547: Support for middle dash in cancel and replace
  src/org/openbravo/erpCommon/businessUtility/CancelAndReplaceUtils.java
  src/org/openbravo/erpCommon/businessUtility/CreateReplacementOrderExecutor.java
Labels: bug

#570 Issue #482: Fix duplicate receipt lines in Landed Cost window
  src-db/database/sourcedata/AD_MESSAGE.xml
  src-test/src/org/openbravo/event/LandedCostDuplicateReceiptValidatorTest.java
  src-test/src/org/openbravo/test/StandaloneTestSuite.java
  src/org/openbravo/event/LandedCostDuplicateReceiptValidator.java
Labels: bug

#568 Feature ETP-125: Add dynamic oracle agent in test pipeline
  pipelines/unittests/JenkinsfileOracle
Labels: enhancement

#581 Issue #553: Fix reservation status in purchase order pre-reservation
  src-test/src/org/openbravo/test/stockReservation/PrereservationTest.java
  src/org/openbravo/common/actionhandler/ManagePrereservationActionHandler.java
Labels: bug

#579 Feature ETP-1017: Implement module with navigation and documentNo logic for 'Create Invoice from Order' window
  modules_core/com.etendoerp.client.application/src-db/database/sourcedata/AD_MODULE.xml
  modules_core/com.etendoerp.client.application/src-db/database/sourcedata/AD_MODULE_DBPREFIX.xml
  modules_core/com.etendoerp.client.application/src-db/database/sourcedata/AD_MODULE_DEPENDENCY.xml
  modules_core/com.etendoerp.client.application/src-db/database/sourcedata/AD_PACKAGE.xml
  modules_core/com.etendoerp.client.application/src/com/etendoerp/client/application/UIComponentProvider.java
  modules_core/com.etendoerp.client.application/web/com.etendoerp.client.application/js/direct-tab-link.js
  modules_core/com.etendoerp.client.application/web/com.etendoerp.client.application/js/sales-order-tab-link.js
  modules_core/com.smf.jobs.defaults/src-db/database/sourcedata/AD_COLUMN.xml
  modules_core/com.smf.jobs.defaults/src-db/database/sourcedata/AD_FIELD.xml
  modules_core/com.smf.jobs.defaults/src-db/database/sourcedata/OBUIAPP_PARAMETER.xml
Labels: enhancement
